Repository kakao-tech-campus-2nd-step3/Team6_BE, pull requests merged in 2024-11, with the labels that each got.

#132 Weekly/7/issue#112 Redis의 방문자수 DB로 동기화하는 Scheduler 구현
  src/main/java/supernova/whokie/global/config/SchedulerConfig.java
  src/main/java/supernova/whokie/profile/ProfileVisitCount.java
  src/main/java/supernova/whokie/profile/ProfileVisitor.java
  src/main/java/supernova/whokie/profile/service/ProfileSchedulerService.java
  src/main/java/supernova/whokie/profile/service/ProfileVisitCountWriterService.java
  src/main/java/supernova/whokie/profile/service/ProfileVisitorWriterService.java
  src/main/java/supernova/whokie/redis/entity/RedisVisitor.java
  src/main/java/supernova/whokie/redis/service/RedisVisitService.java
  src/test/java/supernova/whokie/profile/infrastructure/repository/ProfileVisitorRepositoryTest.java
  src/test/java/supernova/whokie/redis/service/RedisVisitServiceTest.java
Labels: 🌟 feature

#143 Weekly/8/issue#139 프런트엔드 요구사항 반영
  .github/workflows/deploy.yml
  src/main/java/supernova/whokie/ranking/controller/RankingController.java
  src/main/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepository.java
  src/main/java/supernova/whokie/ranking/service/RankingReaderService.java
  src/main/java/supernova/whokie/ranking/service/RankingService.java
  src/main/resources/application-aws.properties
  src/test/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepositoryTest.java
  src/test/java/supernova/whokie/ranking/service/RankingServiceTest.java
Labels: 유저, 🌟 feature, test, 랭킹

#151 weekly/9/issue#150 S3서비스 사용
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/friend/service/dto/FriendModel.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/global/constants/MessageConstants.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/group/controller/GroupController.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/service/dto/GroupMemberModel.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/profile/Profile.java
  src/main/java/supernova/whokie/profile/controller/ProfileController.java
  src/main/java/supernova/whokie/profile/controller/dto/ProfileResponse.java
  src/main/java/supernova/whokie/profile/infrastructure/downloader/CustomMultipartFile.java
  src/main/java/supernova/whokie/profile/infrastructure/downloader/ImageDownloader.java
  src/main/java/supernova/whokie/profile/service/ProfileService.java
  src/main/java/supernova/whokie/profile/service/ProfileWriterService.java
  src/main/java/supernova/whokie/profile/service/dto/ProfileModel.java
  src/main/java/supernova/whokie/profile_answer/controller/ProfileAnswerController.java
  src/main/java/supernova/whokie/profile_question/controller/ProfileQuestionController.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/main/java/supernova/whokie/question/service/dto/QuestionModel.java
  src/main/java/supernova/whokie/ranking/controller/RankingController.java
  src/main/java/supernova/whokie/s3/event/S3EventDto.java
  src/main/java/supernova/whokie/s3/event/S3EventHandler.java
  src/main/java/supernova/whokie/s3/service/S3Service.java
  src/main/java/supernova/whokie/s3/service/dto/S3Command.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/event/UserEventDto.java
  src/main/java/supernova/whokie/user/event/UserEventHandler.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/java/supernova/whokie/user/service/dto/UserModel.java
  src/test/java/supernova/whokie/profile/ProfileIntegrationTest.java
  src/test/java/supernova/whokie/profile/service/ProfileServiceTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: 유저, 🌟 feature

#156 Weekly/9/issue#145 알림 기능 구현
  src/main/java/supernova/whokie/alarm/controller/AlarmController.java
  src/main/java/supernova/whokie/alarm/event/AlarmEventDto.java
  src/main/java/supernova/whokie/alarm/event/AlarmEventListener.java
  src/main/java/supernova/whokie/alarm/service/AlarmService.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/global/config/AsyncConfig.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/point_record/event/PointRecordEventHandler.java
  src/main/java/supernova/whokie/point_record/sevice/PointRecordService.java
  src/main/resources/application.properties
Labels: 🌟 feature

#157 Weekly/9/issue#154 힌트 조회 및 질문 기록 반환값 리팩토링
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/infrastructure/repository/AnswerRepository.java
  src/main/java/supernova/whokie/answer/service/AnswerReaderService.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerModel.java
  src/main/java/supernova/whokie/friend/infrastructure/repository/FriendRepository.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/user/Users.java
Labels: ♻️ refactor, 답하기

#162 Weekly/9/issue#146 포인트 결제 기능 구현
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/global/property/KakaoPayProperties.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/infrastructure/apicaller/PayApiCaller.java
  src/main/java/supernova/whokie/point_record/infrastructure/apicaller/dto/PayApproveInfoResponse.java
  src/main/java/supernova/whokie/point_record/infrastructure/apicaller/dto/PayReadyInfoResponse.java
  src/main/java/supernova/whokie/point_record/sevice/PointRecordService.java
  src/main/java/supernova/whokie/point_record/sevice/dto/PointRecordModel.java
  src/main/java/supernova/whokie/redis/entity/PayToken.java
  src/main/java/supernova/whokie/redis/infrastructure/repository/PayRepository.java
  src/main/java/supernova/whokie/redis/service/PayService.java
  src/main/resources/application-kakao.properties
  src/test/java/supernova/whokie/point_record/sevice/PointRecordServiceTest.java
Labels: 포인트, 🌟 feature

#177 코드 리팩토링
  src/main/java/supernova/whokie/pointrecord/sevice/PointRecordService.java
Labels: ♻️ refactor

#180 weekly/9/issue#179 힌트 구매 시 감소 로그 기록 리팩토링
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/pointrecord/constants/PointConstants.java
  src/main/java/supernova/whokie/user/Users.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
Labels: ♻️ refactor

#193 Weekly/9/issue#192 해당 월의 질문기록이 있는 날짜만 반환해주는 api 구현
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerResponse.java
  src/main/java/supernova/whokie/answer/infrastructure/repository/AnswerRepository.java
  src/main/java/supernova/whokie/answer/service/AnswerReaderService.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerModel.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
Labels: 답하기, 질문, 🌟 feature
