Repository kakao-tech-campus-2nd-step3/Team6_BE, pull requests merged in 2024-09, with the labels that each got.

#16 Feat: init
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/supernova/whokie/WhokieApplication.java
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRequest.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerResponse.java
  src/main/java/supernova/whokie/global/BaseTimeEntity.java
  src/main/java/supernova/whokie/global/dto/GlobalResponse.java
  src/main/java/supernova/whokie/global/dto/PagingResponse.java
  src/main/java/supernova/whokie/group/Groups.java
  src/main/java/supernova/whokie/group/controller/GroupController.java
  src/main/java/supernova/whokie/group/controller/dto/GroupRequest.java
  src/main/java/supernova/whokie/group/controller/dto/GroupResponse.java
  src/main/java/supernova/whokie/group_member/GroupMember.java
  src/main/java/supernova/whokie/group_member/GroupRole.java
  src/main/java/supernova/whokie/group_member/GroupStatus.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberRequest.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberResponse.java
  src/main/java/supernova/whokie/point_record/PointRecord.java
  src/main/java/supernova/whokie/point_record/PointRecordOption.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/controller/dto/PointPurchaseRequest.java
  src/main/java/supernova/whokie/point_record/controller/dto/PointRecordResponse.java
  src/main/java/supernova/whokie/profile/Profile.java
  src/main/java/supernova/whokie/profile/controller/ProfileController.java
  src/main/java/supernova/whokie/profile/controller/dto/ProfileResponse.java
  src/main/java/supernova/whokie/profile_answer/ProfileAnswer.java
  src/main/java/supernova/whokie/profile_answer/controller/ProfileAnswerController.java
  src/main/java/supernova/whokie/profile_answer/controller/dto/ProfileAnswerRequest.java
  src/main/java/supernova/whokie/profile_answer/controller/dto/ProfileAnswerResponse.java
  src/main/java/supernova/whokie/profile_question/ProfileQuestion.java
  src/main/java/supernova/whokie/profile_question/controller/ProfileQuestionController.java
  src/main/java/supernova/whokie/profile_question/controller/dto/ProfileQuestionResponse.java
  src/main/java/supernova/whokie/question/Question.java
  src/main/java/supernova/whokie/question/QuestionStatus.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionRequest.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionResponse.java
  src/main/java/supernova/whokie/ranking/Ranking.java
  src/main/java/supernova/whokie/ranking/controller/RankingController.java
  src/main/java/supernova/whokie/ranking/controller/dto/RankingResponse.java
  src/main/java/supernova/whokie/user/Gender.java
  src/main/java/supernova/whokie/user/Role.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/controller/dto/UserResponse.java
  src/main/resources/application.properties
  src/test/java/supernova/whokie/WhokieApplicationTests.java
Labels: 🌟 feature, ⚙️ setting

#17 Week3/issue#1 포인트 api 추가, 엔티티 수정
  src/main/java/supernova/whokie/point_record/PointRecord.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/controller/dto/PointRecordRequest.java
Labels: ♻️ refactor, 포인트

#23 Week3/issue#3 배포 자동화 관련
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🌟 feature, ⚙️ setting

#18 Week3/issue#4 친구 api, 엔티티 작성
  src/main/java/supernova/whokie/friend/Friend.java
  src/main/java/supernova/whokie/friend/FriendController.java
  src/main/java/supernova/whokie/friend/controller/dto/FriendRequest.java
  src/main/java/supernova/whokie/friend/controller/dto/FriendResponse.java
Labels: 친구, 🌟 feature

#20 Week3/issue#11 전체 질문 조회하기 기능 구현
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRecord.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRequest.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerResponse.java
  src/main/java/supernova/whokie/answer/repository/AnswerRepository.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/global/BaseTimeEntity.java
  src/main/java/supernova/whokie/question/Question.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
Labels: 질문, 🌟 feature

#21 Week3/issue#10 카카오 로그인 기능 구현
  build.gradle
  src/main/java/supernova/whokie/WhokieApplication.java
  src/main/java/supernova/whokie/global/annotation/Authenticate.java
  src/main/java/supernova/whokie/global/auth/JwtInterceptor.java
  src/main/java/supernova/whokie/global/auth/JwtProvider.java
  src/main/java/supernova/whokie/global/config/RestClientConfig.java
  src/main/java/supernova/whokie/global/config/WebConfig.java
  src/main/java/supernova/whokie/global/property/KakaoProperties.java
  src/main/java/supernova/whokie/global/resolver/LoginUserArgumentResolver.java
  src/main/java/supernova/whokie/user/Gender.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/controller/dto/KakaoAccount.java
  src/main/java/supernova/whokie/user/controller/dto/Profile.java
  src/main/java/supernova/whokie/user/controller/dto/TokenInfoResponse.java
  src/main/java/supernova/whokie/user/controller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/repository/UserRepository.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/java/supernova/whokie/user/util/KakaoApiCaller.java
  src/main/resources/application.properties
Labels: 유저, 🌟 feature

#22 Week3/issue#12 내 정보 조회
  src/main/java/supernova/whokie/WhokieApplication.java
  src/main/java/supernova/whokie/global/BaseTimeEntity.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/controller/dto/UserResponse.java
  src/main/java/supernova/whokie/user/service/UserService.java
Labels: 유저, 🌟 feature

#27 Week3/issue#14 내 포인트 조회
  src/main/java/supernova/whokie/user/Role.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/controller/dto/UserResponse.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/java/supernova/whokie/user/util/UserApiCaller.java
  src/test/java/supernova/whokie/user/UserServiceTest.java
Labels: 유저, 🌟 feature

#26 Week3/issue#13 친구 설정
  src/main/java/supernova/whokie/friend/Friend.java
  src/main/java/supernova/whokie/friend/controller/FriendController.java
  src/main/java/supernova/whokie/friend/repository/FriendRepository.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/test/java/supernova/whokie/friend/repository/FriendRepositoryTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/user/repository/UserRepositoryTest.java
Labels: 친구, 🌟 feature

#38 Weekly/4/issue#37 Global 작성
  src/main/java/supernova/whokie/WhokieApplication.java
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/friend/service/FriendKakaoApiCaller.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/global/auth/JwtInterceptor.java
  src/main/java/supernova/whokie/global/config/JpaConfig.java
  src/main/java/supernova/whokie/global/config/RestClientConfig.java
  src/main/java/supernova/whokie/global/config/WebMvcConfig.java
  src/main/java/supernova/whokie/global/entity/BaseTimeEntity.java
  src/main/java/supernova/whokie/global/exception/CustomException.java
  src/main/java/supernova/whokie/global/exception/EntityNotFoundException.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/global/resolver/LoginUserArgumentResolver.java
  src/main/java/supernova/whokie/group/Groups.java
  src/main/java/supernova/whokie/group_member/GroupMember.java
  src/main/java/supernova/whokie/point_record/PointRecord.java
  src/main/java/supernova/whokie/profile_answer/ProfileAnswer.java
  src/main/java/supernova/whokie/profile_question/ProfileQuestion.java
  src/main/java/supernova/whokie/question/Question.java
  src/main/java/supernova/whokie/user/Users.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
Labels: ♻️ refactor, 🌟 feature, ⚙️ setting

#42 Weekly/4/issue#41 카카오 로그인 시 유저 권한 설정
  src/main/java/supernova/whokie/global/auth/JwtInterceptor.java
  src/main/java/supernova/whokie/global/exception/AuthenticationException.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/controller/dto/KakaoAccount.java
  src/main/java/supernova/whokie/user/controller/dto/Profile.java
  src/main/java/supernova/whokie/user/controller/dto/TokenInfoResponse.java
  src/main/java/supernova/whokie/user/controller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/UserApiCaller.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/KakaoAccount.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/Profile.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/TokenInfoResponse.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/test/java/supernova/whokie/user/UserServiceTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: ♻️ refactor, 유저, ⚙️ setting

#55 Weekly/4/issue#52 로그인 로직 변경
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/global/auth/JwtProvider.java
  src/main/java/supernova/whokie/user/Role.java
  src/main/java/supernova/whokie/user/Users.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/controller/dto/UserResponse.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/UserApiCaller.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/Partner.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/java/supernova/whokie/user/service/dto/UserModel.java
  src/test/java/supernova/whokie/user/controller/UserControllerTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: 🛠️ fix, 유저

#47 Weekly/4/issue#46 Friend 로직 변경
  src/main/java/supernova/whokie/friend/Friend.java
  src/main/java/supernova/whokie/friend/controller/FriendController.java
  src/main/java/supernova/whokie/friend/controller/dto/FriendRequest.java
  src/main/java/supernova/whokie/friend/controller/dto/FriendResponse.java
  src/main/java/supernova/whokie/friend/event/FriendEventDto.java
  src/main/java/supernova/whokie/friend/event/FriendEventHandler.java
  src/main/java/supernova/whokie/friend/infrastructure/repository/FriendRepository.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/friend/service/dto/FriendCommand.java
  src/main/java/supernova/whokie/friend/service/dto/FriendModel.java
  src/main/java/supernova/whokie/global/config/AsyncConfig.java
  src/main/java/supernova/whokie/global/exception/BaseException.java
  src/main/java/supernova/whokie/user/repository/UserRepository.java
  src/test/java/supernova/whokie/friend/repository/FriendRepositoryTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/profile/controller/ProfileControllerTest.java
  src/test/java/supernova/whokie/profile/service/ProfileServiceTest.java
  src/test/java/supernova/whokie/user/UsersTest.java
  src/test/java/supernova/whokie/user/controller/UserControllerTest.java
  src/test/java/supernova/whokie/user/repository/UserRepositoryTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: ♻️ refactor, 친구, 🌟 feature

#53 weekly/4/issue#51 포인트 입출력 내역 조회 구현
  src/main/java/supernova/whokie/global/entity/BaseTimeEntity.java
  src/main/java/supernova/whokie/point_record/PointRecord.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/controller/dto/PointRecordResponse.java
  src/main/java/supernova/whokie/point_record/infrastructure/repository/PointRecordRepository.java
  src/main/java/supernova/whokie/point_record/sevice/PointRecordService.java
  src/main/java/supernova/whokie/point_record/sevice/dto/PointRecordCommand.java
  src/main/java/supernova/whokie/point_record/sevice/dto/PointRecordModel.java
  src/test/java/supernova/whokie/point_record/infrastructure/repository/PointRecordRepositoryTest.java
Labels: 포인트, 🌟 feature

#54 weekly/4/issue#50 랭킹 조회 기능 구현
  src/main/java/supernova/whokie/group/Groups.java
  src/main/java/supernova/whokie/group/repository/GroupsRepository.java
  src/main/java/supernova/whokie/ranking/Ranking.java
  src/main/java/supernova/whokie/ranking/controller/RankingController.java
  src/main/java/supernova/whokie/ranking/controller/dto/RankingResponse.java
  src/main/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepository.java
  src/main/java/supernova/whokie/ranking/service/RankingService.java
  src/main/java/supernova/whokie/ranking/service/dto/RankingModel.java
  src/test/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepositoryTest.java
  src/test/java/supernova/whokie/ranking/service/RankingServiceTest.java
Labels: 🌟 feature, 랭킹

#60 Weekly/4/issue#48 프로필 질문 관련 API
  .github/workflows/deploy.yml
  src/main/java/supernova/whokie/global/config/WebMvcConfig.java
  src/main/java/supernova/whokie/global/exception/ForbiddenException.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/profile_answer/ProfileAnswer.java
  src/main/java/supernova/whokie/profile_answer/controller/ProfileAnswerController.java
  src/main/java/supernova/whokie/profile_answer/controller/dto/ProfileAnswerRequest.java
  src/main/java/supernova/whokie/profile_answer/controller/dto/ProfileAnswerResponse.java
  src/main/java/supernova/whokie/profile_answer/infrastructure/repository/ProfileAnswerRepository.java
  src/main/java/supernova/whokie/profile_answer/service/ProfileAnswerService.java
  src/main/java/supernova/whokie/profile_answer/service/dto/ProfileAnswerCommand.java
  src/main/java/supernova/whokie/profile_answer/service/dto/ProfileAnswerModel.java
  src/main/java/supernova/whokie/profile_question/ProfileQuestion.java
  src/main/java/supernova/whokie/profile_question/controller/ProfileQuestionController.java
  src/main/java/supernova/whokie/profile_question/controller/dto/ProfileQuestionResponse.java
  src/main/java/supernova/whokie/profile_question/infrastructure/repository/ProfileQuestionRepository.java
  src/main/java/supernova/whokie/profile_question/service/ProfileQuestionService.java
  src/main/java/supernova/whokie/profile_question/service/dto/ProfileQuestionCommand.java
  src/main/java/supernova/whokie/profile_question/service/dto/ProfileQuestionModel.java
Labels: 질문, 🌟 feature

#35 Week3/issue#2 랜덤 공통 질문 조회하기 기능 구현
  src/main/java/supernova/whokie/friend/infrastructure/repository/FriendRepository.java
  src/main/java/supernova/whokie/question/Question.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionResponse.java
  src/main/java/supernova/whokie/question/repository/QuestionRepository.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/main/java/supernova/whokie/question/service/dto/QuestionModel.java
  src/main/java/supernova/whokie/user/controller/dto/UserResponse.java
  src/main/java/supernova/whokie/user/service/dto/UserModel.java
  src/main/resources/application-common.properties
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
Labels: 질문, 🌟 feature

#36 Week3/issue#9 답변 대상 새로고침 기능 구현 및 통합 테스트 작성
  src/main/java/supernova/whokie/answer/Answer.java
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRecord.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRequest.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerResponse.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerCommand.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerModel.java
  src/main/java/supernova/whokie/friend/infrastructure/repository/FriendRepository.java
  src/main/java/supernova/whokie/question/Question.java
  src/main/resources/application-common.properties
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
Labels: 답하기, 🌟 feature
