Repository kakao-tech-campus-2nd-step3/Team6_BE, pull requests merged in 2024-10, with the labels that each got.

#64 Weekly/5/issue#63 로그인 로직 수정
  README.md
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/global/auth/JwtInterceptor.java
  src/main/java/supernova/whokie/global/config/WebMvcConfig.java
  src/main/java/supernova/whokie/global/resolver/LoginUserArgumentResolver.java
  src/main/java/supernova/whokie/profile/Profile.java
  src/main/java/supernova/whokie/profile_answer/service/ProfileAnswerService.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/UserApiCaller.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/Partner.java
  src/main/java/supernova/whokie/user/infrastructure/apiCaller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/infrastructure/repository/UserRepository.java
  src/main/java/supernova/whokie/user/infrastructure/repository/UsersRepository.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/friend/repository/FriendRepositoryTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/profile/controller/ProfileControllerTest.java
  src/test/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepositoryTest.java
  src/test/java/supernova/whokie/user/controller/UserControllerTest.java
  src/test/java/supernova/whokie/user/repository/UserRepositoryTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: ♻️ refactor, 유저

#70 Weekly/5/issue#65 그룹장 위임 기능
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/group/Groups.java
  src/main/java/supernova/whokie/group_member/GroupMember.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberRequest.java
  src/main/java/supernova/whokie/group_member/infrastructure/repository/GroupMemberRepository.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberService.java
  src/main/java/supernova/whokie/group_member/service/dto/GroupMemberCommand.java
  src/main/java/supernova/whokie/user/Users.java
  src/test/java/supernova/whokie/group_member/controller/GroupMemberControllerTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/user/controller/UserControllerTest.java
Labels: 그룹, 🌟 feature

#73 Weekly/5/issue#71 그룹 멤버 강퇴하기
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/group_member/GroupMember.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberRequest.java
  src/main/java/supernova/whokie/group_member/infrastructure/repository/GroupMemberRepository.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberService.java
  src/main/java/supernova/whokie/group_member/service/dto/GroupMemberCommand.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/group_member/controller/GroupMemberControllerTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
  src/test/java/supernova/whokie/user/controller/UserControllerTest.java
Labels: 그룹, 🌟 feature

#78 Weekly/5/issue#75 그룹 멤버 조회하기
  src/main/java/supernova/whokie/group_member/GroupMember.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberResponse.java
  src/main/java/supernova/whokie/group_member/infrastructure/repository/GroupMemberRepository.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberService.java
  src/main/java/supernova/whokie/group_member/service/dto/GroupMemberModel.java
  src/test/java/supernova/whokie/group_member/controller/GroupMemberControllerTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
Labels: 그룹, 🌟 feature

#82 Weekly/5/issue#81 request 검증 리펙토링
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRequest.java
  src/main/java/supernova/whokie/friend/controller/FriendController.java
  src/main/java/supernova/whokie/friend/controller/dto/FriendRequest.java
  src/main/java/supernova/whokie/global/resolver/LoginUserArgumentResolver.java
  src/main/java/supernova/whokie/group/controller/GroupController.java
  src/main/java/supernova/whokie/group/controller/dto/GroupRequest.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberRequest.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/controller/dto/PointRecordRequest.java
  src/main/java/supernova/whokie/profile/controller/ProfileController.java
  src/main/java/supernova/whokie/profile_answer/controller/ProfileAnswerController.java
  src/main/java/supernova/whokie/profile_answer/controller/dto/ProfileAnswerRequest.java
  src/main/java/supernova/whokie/profile_question/controller/ProfileQuestionController.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionRequest.java
  src/main/java/supernova/whokie/ranking/controller/RankingController.java
  src/main/java/supernova/whokie/user/controller/UserController.java
Labels: ♻️ refactor

#88 Weekly/6/issue#87 랜덤 그룹 질문 불러오기
  src/main/java/supernova/whokie/group_member/controller/dto/GroupMemberResponse.java
  src/main/java/supernova/whokie/group_member/infrastructure/repository/GroupMemberRepository.java
  src/main/java/supernova/whokie/group_member/service/dto/GroupMemberModel.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionResponse.java
  src/main/java/supernova/whokie/question/repository/QuestionRepository.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/main/java/supernova/whokie/question/service/dto/QuestionModel.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
Labels: 그룹, 질문, 🌟 feature

#93 Weekly/5/issue#79 승인/미승인 그룹 질문 목록 불러오기
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/controller/dto/QuestionResponse.java
  src/main/java/supernova/whokie/question/repository/QuestionRepository.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/main/java/supernova/whokie/question/service/dto/QuestionModel.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
Labels: 그룹, 질문, 🌟 feature

#95 Weekly/6/issue#94 랜덤 그룹 질문 답하기
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerRequest.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerCommand.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/question/Question.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
Labels: 답하기, 그룹, 🌟 feature

#104 issue#86 Feat: redis 설정
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/supernova/whokie/global/config/RedisConfig.java
  src/main/java/supernova/whokie/global/property/RedisProperties.java
  src/main/resources/application-redis.properties
  src/main/resources/application.properties
Labels: ⚙️ setting

#111 Weekly/7/issue#110 전체 질문 기록 조회하기 월별로 받아오게 수정
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/repository/AnswerRepository.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
Labels: ♻️ refactor, 답하기, 질문

#115 Weekly/7/issue#114
  src/main/java/supernova/whokie/answer/controller/AnswerController.java
  src/main/java/supernova/whokie/answer/controller/dto/AnswerResponse.java
  src/main/java/supernova/whokie/answer/service/AnswerReaderService.java
  src/main/java/supernova/whokie/answer/service/AnswerService.java
  src/main/java/supernova/whokie/answer/service/AnswerWriterService.java
  src/main/java/supernova/whokie/answer/service/dto/AnswerModel.java
  src/main/java/supernova/whokie/friend/service/FriendReaderService.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/friend/service/FriendWriterService.java
  src/main/java/supernova/whokie/global/config/AppRunner.java
  src/main/java/supernova/whokie/group/controller/GroupController.java
  src/main/java/supernova/whokie/group/service/GroupReaderService.java
  src/main/java/supernova/whokie/group/service/GroupService.java
  src/main/java/supernova/whokie/group/service/GroupWriterService.java
  src/main/java/supernova/whokie/group_member/controller/GroupMemberController.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberReaderService.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberService.java
  src/main/java/supernova/whokie/group_member/service/GroupMemberWriterService.java
  src/main/java/supernova/whokie/point_record/controller/PointRecordController.java
  src/main/java/supernova/whokie/point_record/sevice/PointRecordReaderService.java
  src/main/java/supernova/whokie/point_record/sevice/PointRecordWriterService.java
  src/main/java/supernova/whokie/profile/service/ProfileReaderService.java
  src/main/java/supernova/whokie/profile/service/ProfileService.java
  src/main/java/supernova/whokie/profile_answer/service/ProfileAnswerReaderService.java
  src/main/java/supernova/whokie/profile_answer/service/ProfileAnswerService.java
  src/main/java/supernova/whokie/profile_answer/service/ProfileAnswerWriterService.java
  src/main/java/supernova/whokie/profile_question/service/ProfileQuestionReaderService.java
  src/main/java/supernova/whokie/profile_question/service/ProfileQuestionService.java
  src/main/java/supernova/whokie/profile_question/service/ProfileQuestionWriterService.java
  src/main/java/supernova/whokie/question/controller/QuestionController.java
  src/main/java/supernova/whokie/question/service/QuestionReaderService.java
  src/main/java/supernova/whokie/question/service/QuestionService.java
  src/main/java/supernova/whokie/question/service/QuestionWriterService.java
  src/main/java/supernova/whokie/question/service/dto/QuestionModel.java
  src/main/java/supernova/whokie/user/service/UserReaderService.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/java/supernova/whokie/user/service/UserWriterService.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/profile/service/ProfileServiceTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
Labels: ♻️ refactor

#122 Weekly/7/issue#112 프로필 조회할 때 방문하도록 구현
  src/main/java/supernova/whokie/global/annotation/VisitorIp.java
  src/main/java/supernova/whokie/global/config/WebMvcConfig.java
  src/main/java/supernova/whokie/global/interceptor/IpInterceptor.java
  src/main/java/supernova/whokie/global/interceptor/JwtInterceptor.java
  src/main/java/supernova/whokie/global/resolver/IpArgumentResolver.java
  src/main/java/supernova/whokie/profile/ProfileVisitCount.java
  src/main/java/supernova/whokie/profile/controller/ProfileController.java
  src/main/java/supernova/whokie/profile/controller/dto/ProfileResponse.java
  src/main/java/supernova/whokie/profile/service/ProfileService.java
  src/main/java/supernova/whokie/profile/service/dto/ProfileModel.java
  src/main/java/supernova/whokie/redis/entity/RedisVisitCount.java
  src/main/java/supernova/whokie/redis/entity/RedisVisitor.java
  src/main/java/supernova/whokie/redis/repository/RedisVisitCountRepository.java
  src/main/java/supernova/whokie/redis/repository/RedisVisitorRepository.java
  src/main/java/supernova/whokie/redis/repository/VisitCountRepository.java
  src/main/java/supernova/whokie/redis/repository/VisitorRepository.java
  src/main/java/supernova/whokie/redis/service/RedisVisitService.java
  src/main/java/supernova/whokie/redis/service/dto/RedisCommand.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/test/java/supernova/whokie/profile/ProfileIntegrationTest.java
  src/test/java/supernova/whokie/profile/service/ProfileServiceTest.java
  src/test/java/supernova/whokie/redis/service/RedisVisitServiceTest.java
Labels: 🌟 feature

#125 Weekly/7/issue#121 테스트 코드 리팩토링
  src/main/java/supernova/whokie/global/auth/JwtProvider.java
  src/main/java/supernova/whokie/user/controller/UserController.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/resources/application-common.properties
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: ♻️ refactor, test

#129 Weekly/7/issue#127 s3 이미지 업로드 및 signed url 생성
  build.gradle
  src/main/java/supernova/whokie/friend/infrastructure/apicaller/FriendKakaoApiCaller.java
  src/main/java/supernova/whokie/friend/infrastructure/apicaller/dto/KakaoDto.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/global/constants/Constants.java
  src/main/java/supernova/whokie/global/exception/FileTypeMismatchException.java
  src/main/java/supernova/whokie/global/exception/GlobalExceptionHandler.java
  src/main/java/supernova/whokie/global/property/AwsS3Properties.java
  src/main/java/supernova/whokie/redis/infrastructure/repository/AccessTokenRepository.java
  src/main/java/supernova/whokie/redis/infrastructure/repository/RedisVisitCountRepository.java
  src/main/java/supernova/whokie/redis/infrastructure/repository/RedisVisitorRepository.java
  src/main/java/supernova/whokie/redis/infrastructure/repository/RefreshTokenRepository.java
  src/main/java/supernova/whokie/redis/service/KakaoTokenService.java
  src/main/java/supernova/whokie/redis/service/RedisVisitService.java
  src/main/java/supernova/whokie/s3/infrastructure/s3servicecaller/S3ServiceCaller.java
  src/main/java/supernova/whokie/s3/service/S3Service.java
  src/main/java/supernova/whokie/s3/service/dto/S3Command.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/UserApiCaller.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/dto/KakaoAccount.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/dto/Profile.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/dto/RefreshedTokenInfoResponse.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/dto/TokenInfoResponse.java
  src/main/java/supernova/whokie/user/infrastructure/apicaller/dto/UserInfoResponse.java
  src/main/java/supernova/whokie/user/service/UserService.java
  src/main/resources/application-aws.properties
  src/main/resources/application.properties
  src/test/java/supernova/whokie/WhokieApplicationTests.java
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/friend/repository/FriendRepositoryTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/group_member/GroupMemberIntegrationTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/profile/ProfileIntegrationTest.java
  src/test/java/supernova/whokie/profile/service/ProfileServiceTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/question/service/QuestionServiceTest.java
  src/test/java/supernova/whokie/ranking/service/RankingServiceTest.java
  src/test/java/supernova/whokie/redis/service/KakaoTokenServiceTest.java
  src/test/java/supernova/whokie/redis/service/RedisVisitServiceTest.java
  src/test/java/supernova/whokie/user/UserIntegrationTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: 🌟 feature, ⚙️ setting

#136 Weekly/8/issue#135 7주차 리뷰 리펙토링
  src/main/java/supernova/whokie/answer/infrastructure/repository/AnswerRepository.java
  src/main/java/supernova/whokie/answer/service/AnswerReaderService.java
  src/main/java/supernova/whokie/answer/service/AnswerWriterService.java
  src/main/java/supernova/whokie/friend/event/FriendEventDto.java
  src/main/java/supernova/whokie/friend/event/FriendEventHandler.java
  src/main/java/supernova/whokie/friend/infrastructure/repository/FriendRepository.java
  src/main/java/supernova/whokie/friend/service/FriendReaderService.java
  src/main/java/supernova/whokie/friend/service/FriendService.java
  src/main/java/supernova/whokie/friend/service/FriendWriterService.java
  src/main/java/supernova/whokie/group/infrastructure/repository/GroupRepository.java
  src/main/java/supernova/whokie/group/infrastructure/repository/dto/GroupInfoWithMemberCount.java
  src/main/java/supernova/whokie/group/service/GroupReaderService.java
  src/main/java/supernova/whokie/group/service/GroupService.java
  src/main/java/supernova/whokie/group/service/GroupWriterService.java
  src/main/java/supernova/whokie/group/service/dto/GroupModel.java
  src/main/java/supernova/whokie/question/infrastructure/repository/QuestionRepository.java
  src/main/java/supernova/whokie/question/service/QuestionReaderService.java
  src/main/java/supernova/whokie/question/service/QuestionWriterService.java
  src/main/resources/application-default.properties
  src/test/java/supernova/whokie/answer/AnswerIntegrationTest.java
  src/test/java/supernova/whokie/answer/service/AnswerServiceTest.java
  src/test/java/supernova/whokie/friend/repository/FriendRepositoryTest.java
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
  src/test/java/supernova/whokie/group_member/GroupMemberIntegrationTest.java
  src/test/java/supernova/whokie/group_member/service/GroupMemberServiceTest.java
  src/test/java/supernova/whokie/question/QuestionIntegrationTest.java
  src/test/java/supernova/whokie/ranking/infrastructure/repoistory/RankingRepositoryTest.java
  src/test/java/supernova/whokie/ranking/service/RankingServiceTest.java
  src/test/java/supernova/whokie/user/repository/UserRepositoryTest.java
  src/test/java/supernova/whokie/user/service/UserServiceTest.java
Labels: ♻️ refactor, test

#134 Weekly/8/issue#133 Friend 저장 및 삭제하는 로직 리펙토링
  src/test/java/supernova/whokie/friend/service/FriendServiceTest.java
Labels: ♻️ refactor, 친구
